### ISSUE TITLE
Error, why?

### ISSUE THREAD

**Issue by EduMts** [ClickedTran/WarpGUI#1]
gave me that error:
I guess it's because of the InvMenu idk

TypeError: "explode(): Argument #2 ($string) must be of type string, array given" (EXCEPTION) in "plugins/WarpGUI-PM4.phar/src/ClickedTran/WarpGUI/WarpGUI" at line 124

**Comment by ClickedTran** [comment]
I think you have an InvMenu problem or you don't have InvMenuCrashFix installed

**Comment by ClickedTran** [comment]
Please download the latest plugin at: https://poggit.pmmp.io/p/WarpGUI/
To avoid the error and also report the error to me, thanks
