### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by SamOmy** [ClickedTran/WarpGUI#2]
Hi, so I've just downloaded the plugin and its working great, IF you set it up correctly. Now you might think that's right you have to set it up correctly, but if I give permissions to everyone to use it then its not ok. Because if someone doesn't know they have to finish setting it up they could just crash the server, and I wouldn't like that. So instead of crashing the server could you make it so that it sends a message "You have to finish up setting it up" or something instead of the server crashing. The plugin works just fine if you set the warps up correctly.
 
 example in the vid bellow.

https://user-images.githubusercontent.com/111495200/186618446-c08593a0-b3c2-4014-b0f4-0c423fdc957b.mov

**Comment by ClickedTran** [comment]
My team and I will look into this, it might take a while since we're busy studying and taking exams
Can you send me the video, we can't see it on here

**Comment by ClickedTran** [comment]
> Hi, so I've just downloaded the plugin and its working great, IF you set it up correctly. Now you might think that's right you have to set it up correctly, but if I give permissions to everyone to use it then its not ok. Because if someone doesn't know they have to finish setting it up they could just crash the server, and I wouldn't like that. So instead of crashing the server could you make it so that it sends a message "You have to finish up setting it up" or something instead of the server crashing. The plugin works just fine if you set the warps up correctly.
> 
> example in the vid bellow.
> 
>  RPReplay_Final1661415934.mov

I'm fixed
