### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by CoolCuzzy** [ClickedTran/WarpGUI#3]
Occurs when the /warp warp command is run, as i assumed it would of opened the gui, could you fix this?

26.09 06:11:39 [Server] INFO [06:11:39.222] [Server thread/CRITICAL]: TypeError: "explode(): Argument #2 ($string) must be of type string, array given" (EXCEPTION) in "plugins/WarpGUI-PM4.phar/src/ClickedTran/WarpGUI/gui/GUIManager" at line 26
26.09 06:11:39 [Server] INFO --- Stack trace ---
26.09 06:11:39 [Server] INFO #0 plugins/WarpGUI-PM4.phar/src/ClickedTran/WarpGUI/gui/GUIManager(26): explode(string[1] :, array[0])
26.09 06:11:39 [Server] INFO #1 plugins/WarpGUI-PM4.phar/src/ClickedTran/WarpGUI/commands/WarpGUICommands(111): ClickedTran\WarpGUI\gui\GUIManager->menuWarpGUI(object pocketmine\player\Player#28350)
26.09 06:11:39 [Server] INFO #2 pmsrc/src/command/SimpleCommandMap(205): ClickedTran\WarpGUI\commands\WarpGUICommands->execute(object pocketmine\player\Player#28350, string[4] warp, array[1])
26.09 06:11:39 [Server] INFO #3 pmsrc/src/Server(1448): pocketmine\command\SimpleCommandMap->dispatch(object pocketmine\player\Player#28350, string[9] warp warp)
26.09 06:11:39 [Server] INFO #4 pmsrc/src/player/Player(1410): pocketmine\Server->dispatchCommand(object pocketmine\player\Player#28350, string[9] warp warp)
26.09 06:11:39 [Server] INFO #5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(754): pocketmine\player\Player->chat(string[10] /warp warp)
26.09 06:11:39 [Server] INFO #6 pmsrc/vendor/pocketmine/bedrock-protocol/src/CommandRequestPacket(51): pocketmine\network\mcpe\handler\InGamePacketHandler->handleCommandRequest(object pocketmine\network\mcpe\protocol\CommandRequestPacket#289655)
26.09 06:11:39 [Server] INFO #7 pmsrc/src/network/mcpe/NetworkSession(409): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#282686)
26.09 06:11:39 [Server] INFO #8 pmsrc/src/network/mcpe/NetworkSession(372): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\CommandRequestPacket#289655, string[31] M./warp warp.qH..M....zE.3.....)
26.09 06:11:39 [Server] INFO #9 pmsrc/src/network/mcpe/raklib/RakLibInterface(182): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[32] ..../O,*P....../..<..Q..........)
26.09 06:11:39 [Server] INFO #10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[41] .B.2b..o._.....%...H4..5f)..r.S.PS7.....o)
26.09 06:11:39 [Server] INFO #11 pmsrc/src/network/mcpe/raklib/RakLibInterface(112): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#26554)
26.09 06:11:39 [Server] INFO #12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
26.09 06:11:39 [Server] INFO #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
26.09 06:11:39 [Server] INFO #14 pmsrc/src/Server(1707): pocketmine\snooze\SleeperHandler->sleepUntil(float 1664172699.2541)
26.09 06:11:39 [Server] INFO #15 pmsrc/src/Server(1065): pocketmine\Server->tickProcessor()
26.09 06:11:39 [Server] INFO #16 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[48] /, string[56] /plugins/)
26.09 06:11:39 [Server] INFO #17 pmsrc/src/PocketMine(328): pocketmine\server()
26.09 06:11:39 [Server] INFO #18 pmsrc(11): require(string[97] phar:///PMMP-Latest-Stable.phar/s)
26.09 06:11:39 [Server] INFO --- End of exception information ---

**Comment by ClickedTran** [comment]
Are you sure you have the item or block installed for that warp?, Please try again
